### ISSUE TITLE
settings.xml

### ISSUE THREAD

**Issue by VoOoLoX** [toddw123/RotMG_Clientless#1]
For some reason when debugging, settings.xml needs to be in the root directory of the project.
Perhaps add that to .gitignore ?

**Comment by Zeroeh** [comment]
The root directory or the debug directory?
Also, just add .xml to the gitignore list, but this will only prevent you from uploading it during a pull request.

**Comment by toddw123** [comment]
So the latest gitignore should ignore all instances of "settings.xml" no matter where you place it. I deleted the settings.xml from my root folder before i pushed this project up to github though so thats why there wasnt a settings.xml or settings-sample.xml or anything in the root originally. I would also suggest adding a post-build event that copies the latest settings.xml from the resource folder to your root folder (i had a post-build event that placed it in the target output directory, but not root folder).
