### ISSUE TITLE
Add project TODO ?

### ISSUE THREAD

**Issue by Zeroeh** [toddw123/RotMG_Clientless#22]
Now that the most of the big stuff is out of the way (multiclient, all packets)
Besides adding the rest of the objects and parsing them and whatnot, is there anything left? A project todo would be very nice to have in this case :3

**Comment by toddw123** [comment]
Ill try to get a few things put on a todo list tomorrow. Right now im working on parsing the object.xml, after then i havent decided what is after that. Probably start figuring out how to best track projectiles so as to send the playerhit/enemyhit/otherhit packets correctly. After tracking projectiles it will probably be tracking other onscreen objects like mobs/bags/players/portals/etc. RIght now all that data is received but none of it is stored for use.

**Comment by toddw123** [comment]
Okay i created a few "Projects" with some of the to do's and whatnot. Most of the things on my todo list are really just to research/come up with the best way to do some of the upcoming tasks. So some of the todo's are more of an "open discussion" more then actual work. Although coming up with some concepts/pseudo-code for them would be extremely welcomed.
