### ISSUE TITLE
post your loot

### ISSUE THREAD

**Issue by toddw123** [toddw123/RotMG_Clientless#32]
I like seeing what people have amassed with their lootbots. So lets have this be the official thread/issue/whatever for that. 

Anyways, here is my lootbots loot for the past few weeks or so. I created a second muledump accounts.js file just for my bots so i could easily track what they have gotten.

![Lootbots](http://imgur.com/JZeBPLF.png)

And yes, i am just as shocked as you all are that people would drop a deca ring, pixie, etherite, and all that other shit. Its crazy to me. 

Also i did originally drink enough speed and dex pots to max an assassin before this was taken, so thats an extra like 20 pots each that this image is missing. And whatever else.

So lets see it, show me what cool shit youve managed to get with the lootbot branch!

**Comment by Zeroeh** [comment]
Lol you can thank my friend for dropping the deca ring, pixie, and etherite. (doing some testing)

But damn, it's amazing how little people care about dex.

**Comment by toddw123** [comment]
Your friend dropped those items? Are you sure it was me that got them when he did it? I got all 3 of those 2-3 weeks back, and on different days i believe. The etherite was first, then the deca ring, then the pixie lol.

Did you friend also drop the UBMP/UBVIT? I was a little surprised over those rings as well. They arent worth a whole lot, but they arent worthless by any means.

And yes im shocked at how much people just toss out dex. Im also surprised that speed and wis are about the same, but really im mostly confused at why anyone would drop stuff in the first place. But hey whatever, more stuff for me!

edit: oh and the UT "The Forgotten Ring" lol. This ring was being dropped a ton because of the Twilight Redux Box or whatever. I noticed that when that box was active that i was getting atleast 1 a day. Ill have to keep my eyes on this next time i see a box with something crappy in it. See if i get that crappy item more when the box is out or something.

edit: wow. just got another pixie on one of my bots. amazing lol thats 2 pixies now

**Comment by jalius** [comment]
24 hours and i pulled a similar haul. just 2 STs. for the record im running 50 bots, a big portion of them at uswest2 and eunorth2. not sure if its faulty code or the lack of players is to blame, but many of my bots on the less populated servers got 0. while this is fun to run and debug, I don't think its even going to be paying the electricity bill, lol.

**Comment by toddw123** [comment]
i have bots on various servers that only seem to get 1 or 2 items a day max, its just due to the server being less populated. Im still running 3 bots per server for every server, so some of them get tons of stuff others get just a little. I have no desire to make profit off the items i get, i just find it cool that i can have this program running in the background on my computer and slowly get items all day. It still rarely passes 2% cpu usage for me, and since the memory leaks have been fixed i havent had it crash on me and the memory doesnt go past 8MB at its highest. So just fun to play with for me.

**Comment by jalius** [comment]
https://www.reddit.com/r/RotMG/comments/5y6dxp/a_swarm_of_loot_bots/
This you @toddw123 ?

**Comment by jalius** [comment]
Too much network or CPU usage going on for whoever  was running that bot. Wonder why they have 8 bots on that unpopulated server.

**Comment by toddw123** [comment]
Possibly me but idk for sure. My bots will change server if they are DC'ed too much or the server is down. So when you have 66ish bots, I can see it happening. The return to the middle is 100% my code, just don't know who else is running this stuff. I know someone was playing with it yesterday so could of been them too. 

CPU wise, no problem. But I can see network being a problem for me, pushing ~2mbps up when I only have about 3mbps up probably...Yeah def could be me and network slowing them down. But hey, still get loot so whatever lol

**Comment by jalius** [comment]
im only doing 5000 Bytes up, wonder how you are sending 2 megabits (or bytes?) is the resource monitor an accurate representation of my upload data?

**Comment by toddw123** [comment]
guess its 2 total, not just up. so up probably isnt that much. But i just did a speedtest to double check and i actually only have 1mbps up (seems most ISPs only focus on giving down speed and not up speed for homes). 20 down, 1 up.  So even using just a fraction of that up speed severely scews with speed. I know when im downloading torrents i refuse to allow more then 10kbps up because the more im sending up the less i can get down. 

I have made a few changes to the bot though, some of them are live already and the rest im pushing soon. The first part ive added is to limit the number of bots per server. As soon as one of the clients connects to a server it updates a stored variable with the server its on, then whenever im looking for a new server to connect to on a client i will first get a random server, then if that random server has more then 6 bots on it i will select a different random server until i find one that has less. Then i also added a population counter. If the current population onscreen is less then 15 the bots will switch to a different server. I want to change this so it scales the number of allowed bots based on population, but havent gotten that far yet lol

**Comment by jalius** [comment]
How many bytes are you getting up? I'm only getting 2000, that's like .002 megabytes.

**Comment by jalius** [comment]
Down however, getting 100,000 bytes, which is only .01 MB (right?). One of us is wrong with our upload and download speeds, lol.

**Comment by toddw123** [comment]
So my entire traffic on my laptop (which i dont have much else running besides the bots, but there is obviously some other stuff) is currently 400 kbps up. Which is 0.4mbps. And i have 1mbps up. So thats nearly half my up speed, which slows down everything really. I notice it alot when trying to browse websites because they will load slower. But meh oh well.

**Comment by toddw123** [comment]
![more lootbot](http://i.imgur.com/SWEA560.png)

Heres the latest as of like a day ago since i havent had them running very much the last 2-3 days. And theres no point in running them right now since everything is soulbound lol

I like how in less then a week i doubled all of the stat pots pretty much. I think this is ~2 weeks of lootbots running anywhere from 4-12 hours a day. Some of the good ideas i traded over to my main account just so i wouldnt lose them somehow. I think the only items i traded over are the deca ring, 2 pixies, etherite, 1 t6 trap (idk why though), 1 ubmp, 1 ubvit, and that is it. So this is everything but those items. 

I also like to play around and equip rings on my bots. If you ever see a lootbot with a forgotten ring on its probably mine, or i have the ubspd rings on a couple of them lol. 

I think the best item ive gotten recently is the staff of rising sun. The rest is just filler really. Still makes me laugh that so many people drop shit like this. And i really dont get why people just toss their forgotten rings, fucking 24 of them...and t12 katanas! I get one a day atleast! lol

**Comment by jalius** [comment]
I was thinking I would make a trade bot that takes people items and gives them out to noobs :) I know it's possible, so much data is passed to us through update packet about the player. I would have a star check, a level check, a name record, an inv scanner, stats checker, and if they meet the criteria, I would send them a free item donated by someone else. Seems really fucking useless, but I think it's going to be fun. And maybe I can skim off the top if it becomes actually popular.

**Comment by toddw123** [comment]
So are you saying its a bot that would accept trades from people who are higher level/star, and they could trade whatever items they want to the bot. Then someone low level or new could trade the bot and it would trade them an item(s)?

Its completely possible if thats what you are talking about. I would create a Player class, or something similar to that, then create a map <int,Player> to store all the people on screen. The update packet contains a fuckton of data on each player so you would just have to store that. The newtick packet also contains data on players too, but it doesnt add new players it only updates existing player (the update packet does both), atleast i think thats how it works. 

The problem is when someone trades you a ton of junk so you are full, then no one else can trade you anything good until you trade it off to noobs (or drop it). 

I also think people would be very hesitant to trust a bot claiming to do what you are saying, they would just assume its a scam.
