### ISSUE TITLE
Items dropped from players will now be in SB bags. Use the Trade feature to trade items with other players!

### ISSUE THREAD

**Issue by jalius** [toddw123/RotMG_Clientless#37]
https://www.reddit.com/r/RotMG/comments/5ygzqt/patch_notes_277x111_the_fixening/

they just killed 2 birds with 1 stone. (killed duping and as a side effect, this lootbot branch)

**Comment by toddw123** [comment]
Wow. Well, this is just for now. I wouldnt be surprised if people complain enough that they reverse this.

Oh well, now ill just be focusing on the master branch then instead of the lootbot branch.

**Comment by jalius** [comment]
it will probably remain like that, because it is a combat against duping. unless they can figure another fix, but i think this is the easiest for them. just a heads up :)

**Comment by toddw123** [comment]
Its a band-aid, not a fix. A true fix would be to correct the code so the dupe isnt possible while the rest of the game remains the same. This is a band-aid where they changed the functionality of something else in order to prevent the duping. Its a horrible way to go about coding. So hopefully the will stop being lazy and actually make a real fix, then they can remove the soulbound shit. 

Plus, im pretty sure trading is involved in the dupe, so im not sure how this is suppose to be a fix...oh well.

**Comment by toddw123** [comment]
You can even see in their post they say: "Is that going to be forever? We can’t say for sure". I think this is just their way of creating a temporary fix until they solve the real issues going on. I just hope there is enough backlash from the community that it does get reversed.

**Comment by jalius** [comment]
Yes it's a band-aid fix, but it does kill a dupe (I'm sure). I think it's not entirely their fault that the code is confusing, they do have 2 previous teams and 6 years of code to decipher.

**Comment by alanbaumgartner** [comment]
Heres to hoping they stick to what they said and recode the game into a more applicable language.

**Comment by ebf34e12952930cf** [comment]
@AlanBaumgartner its only the client thats a problem, really

**Comment by alanbaumgartner** [comment]
@BlackRayquaza That's what I meant, my desktop is shit.

**Comment by jalius** [comment]
we can actually do this as players. scellow and many people already made less laggy clients.

**Comment by Zeroeh** [comment]
What are you trying to say?

**Comment by jalius** [comment]
Google "scellow 3D client".
https://youtube.com/watch?v=9ee1xwEi2BA

From there you can view all the other vids of his clients.

**Comment by Zeroeh** [comment]
What do you mean "we can actually do this as players"?

**Comment by jalius** [comment]
@Zeroeh Alan said, "Heres to hoping they stick to what they said and recode the game into a more applicable language," to which I replied with, "we can do this as players". I wasn't very clear, I meant that we did not have to wait for deca to create a new client, because the players could make this themselves.
