### ISSUE TITLE
Visual Studios 2017!

### ISSUE THREAD

**Issue by toddw123** [toddw123/RotMG_Clientless#40]
Hey guys just wanted to post that visual studios 2017 is out. I have it on my computer already and want to let you guys know just incase you were interested. I just went with the free Community edition (same version i was using for 2015 and never had any problems). The main reason i switched over was because i was trying to figure out how i could cross-compile to linux. What i really wanted was a way to convert the project into a make file so i could then build on linux (which means i could run the program on a server). I did find this interesting article that lead me to download vs2017: https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#consoleapp

The article is interesting and goes over how in the newest version you can actually create projects specifically for linux. I use a VM on my computer for work since i do PHP and i feel its better to use linux when developing since all the servers i deploy too are linux based. Anyways, i was able to use the VM in the same manor that the article talks about and i could compile a project for linux. I think that is super cool. 

The only thing that sucks is it looks like there is no way for me to take an existing project and do this with it. So as cool as that is, its not that helpful. If anyone has any experience compiling larger projects on linux and wants to help set this project up so it can be easily compiled that would be cool. I think the largest c++ program ive compiled on linux involved like 7 or 8 files, so nowhere near as many as this one haha. 

Oh and another reason i wanted to mention visual studios 2017 was due to the fact that a few settings in the project file got changed when i opened the project up. Im going to try and prevent this, but just a heads up incase anyone has some kind of issue opening the project.

Theres a lot more that i would love to talk about in regards to visual studios 2017 but i honestly havent even played around with it for more then a few hours yesterday. When installing it offers a fuckton of optional sdks/extension/etc. You are able to install mobile development sdks for android/ios, it had the option to install unity and unity related crap (unity is a very big game engine that people like). Just a lot of cool stuff like that. I know all of these things could be installed and used with 2015, but i dont recall having the option to download/install these things at the same time it was installing visual studios. But meh whatever.

edit: im actually playing around with Unity for the first time ever, its pretty interesting. I dont really like that the only languages you can use with Unity are C# or Javascript (seriously, javascript lol). But oh well, its still pretty neat. Im just going through a couple tutorials on using unity to have a little fun. Then i need to get back to working on this project lol

**Comment by VoOoLoX** [comment]
I've been using VS 2017 for past month or so (RC build), it has noticeable speed improvements when loading solutions and projects.But the main feature why I switched is Ctrl+T

**Comment by toddw123** [comment]
What the hell does Ctrl+T do? i just tried, it seems it switches the character at the caret position with the one right before it? So if you have () and your caret is just after the ), pressing ctrl+t turns it into )(

Or does it do something else and im missing it? lol

**Comment by VoOoLoX** [comment]
http://i.imgur.com/vSN38xS.png

**Comment by toddw123** [comment]
Ah interesting. So they basically added the same feature from Sublime Text. Very cool

**Comment by Zeroeh** [comment]
Honestly, I think I'll be skipping out on this version of visual studio like I did on 2013. There are nice improvements each new VS, but it's annoying having to install 30+GB of application and whatnot every year or two. If I see a real benefit to moving over, I'll do so, but 2017 doesn't have what I wanted.
