### ISSUE TITLE
fiverr.com? wtf?

### ISSUE THREAD

**Issue by toddw123** [toddw123/RotMG_Clientless#42]
I dont know if everyone can see it or not, but if you go to Graphs and then Traffic you can see the where visitors have come from:
![Traffic](http://i.imgur.com/GRqwTlo.png)

lol wtf? When you click on one of the referrers it will actually show you a more unique url if possible, and it looks like someone was having a conversation with someone on fiverr and linked to this project? Was that any of you? I have no idea what the "com.google.android.gm" one is. The Hackforums.net i actually went and found the post linking to this project a few weeks ago, it was actually someone from mpgh that used that site and had posted asking for help with a link to this project as a reference as to what they were wanting to do or something. So i can understand the hackforums.net, i can understand google, and obviously i can understand github. But fiverr? Seriously? I am so lost.

Oh and when you click on the fiverr link, the reason i say that it might of been in someones conversation is because it shows the unique url of " /conversations/ognsai".  I searched fiverr for "ognsai" but couldnt find any reference to that, so no idea if that is a person or what the hell it is. 

edit: actually, once i was able to login to fiverr (i created an account years ago but never did anything with it because it seems pretty stupid imo) i had a random spam message from somone. When i opened that spam message i saw the url looked exactly like the url i posted above: "/conversations/[username]". I switched out the username with "ognsai" and it brought me to the persons profile: https://www.fiverr.com/ognsai

WHO ARE YOU?! WHY WERE YOU TALKING ABOUT THIS PROJECT?! Lol seriously though wtf.

**Comment by Zeroeh** [comment]
I can't see the traffic part? 
http://prntscr.com/elan8q

**Comment by toddw123** [comment]
well, thats why the very first thing i said was "I dont know if everyone can see it or not" and then posted a picture incase you cant.

**Comment by Zeroeh** [comment]
Was interested in the hackforums link. I found it though
https://hackforums.net/showthread.php?tid=5562149&highlight=RotMG_Clientless
Might even try a python clientless haha

**Comment by toddw123** [comment]
it doesnt show url parameters just that it came from /showthread.php when you click on the hackforums.com referrer. And yup thats the link, you can see i created an account to post in that thread saying it was my project. But thats all ive looked at on that site.

**Comment by Zeroeh** [comment]
As for the other links, the internet can bring up the most random things sometimes...

**Comment by toddw123** [comment]
well someone clearly sent this project in a conversation on fiverr, which is what im most interested in. Like what was the conversation about? Why did this project get brought up? Lol seriously, like wtf?

the other referrers i dont care about. No idea what the com.blablabla one is, but the rest are normal like i said.

**Comment by Zeroeh** [comment]
Probably someone who couldn't code asking for help, seeing as how the site is for freelancing.

**Comment by toddw123** [comment]
Calling it freelancing is being pretty generous. It's mostly people offering to do stupid shit for $5. But yes there are some random code related things on there like "I'll do your class assignment for $5" or "I'll write a script to blahblahblah". 

But still, reallllly interested in finding out for sure what brought this project into the conversation lol.

**Comment by alanbaumgartner** [comment]
Not sure about the fiver one but I am Folks from HF. I actually haven't used the site for a long time until I posted that. Python is what I have most acquainted with I was looking into working on it, haven't made too much progress due to school though.
