### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by VoOoLoX** [toddw123/RotMG_Clientless#49]
After few hours of trying I got it to compile on Ubuntu 16.04 and Lubuntu 17.04

## Lubuntu 17.04: (CMake 3.7.2, GCC/G++ 6.3.0 20170406)

- Install cmake `sudo apt install cmake`
- Install g++ `sudo apt install g++`
- Install ssl dev `sudo apt install libssl-dev`
- Install curl dev `sudo apt install libcurl4-openssl-dev`

OR
- Install all at once `sudo apt install cmake g++ libssl-dev libcurl4-openssl-dev` in case you are too lazy to copy paste multiple commands

- Get the source
- cd into root directory of the source
- Run `cmake .`
- Run `make`

- USE ONLY IN CASE OF EXTREME LAZINESS (NOT TESTED) (SINGLE COMMAND) `sudo apt install git cmake g++ libssl-dev libcurl4-openssl-dev && git clone https://github.com/toddw123/RotMG_Clientless.git && cd RotMG_Clientless && cmake . && make`

## Ubuntu 16.04 LTS:

- Add testing repo/ppa `sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
- Update `sudo apt update`
- Install cmake `sudo apt install cmake`
- Install ssl dev `sudo apt install libssl-dev`
- Install curl dev `sudo apt install libcurl4-openssl-dev`
- Install gcc/g++ 6 `sudo apt install g++-6`
- Change link from gcc-5/g++-5 to gcc-6/g++-6 using `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6`
- Check gcc/g++ version using `gcc --version` it should be 6.2 or higher if it's not run `sudo update-alternatives --config gcc`

- Get the source
- Edit `CMakeLists.txt` > Change minimum CMake version to `3.5`
- cd into root directory of the source
- Run `cmake .`
- Run `make`

### Let me know if there are any problems with any of the steps

**Comment by toddw123** [comment]
very cool ill give this a try on Xubuntu later today. I assume the main reason it wouldnt compile before is just due to not having the latest version of the different programs. So ill give this a try.

Also, it would be really cool if you wanted to make a page in the Wiki for compiling on Linux. You can make the first part about compiling on Arch Linux, which seems pretty straight forward. Then feel free to add the content from this post, as i have no doubt what you are saying here does work.

**Comment by VoOoLoX** [comment]
I thought about making a wiki page but I want to verify that these steps work on most systems first.
I tested both of these in virtual machine with fresh installs and all the updates.
So I guess I'll try it on a real hardware on the other pc and/or wait for your feedback on Xubuntu.

**Comment by toddw123** [comment]
@VoOoLoX Alright man, sorry it took me so long, but i finally got around to testing on Xubuntu. I followed exactly what you had laid out for the Ubuntu 16.04 LTS and it worked flawlessly.

There were a few warning, but they are just warnings. I think the only warnings come from the xml reader, in the `printf` statements upon error there are a few `%i` variables, which expects `int`, but apparently is some kind of long instead. Nothing that will break the program though thats for sure.

The only other message that i get, both when the compiling is finished and when i start the program, is this:
> [/usr/bin/cmake OR ./Clientless]: /usr/local/lib/libcurl.so.4: no version information available (required by [/usr/bin/cmake OR ./Clientless])

So when i compiling, it will start with the "/usr/bin/cmake" and end with it, and when i start the actual compiled program it starts with "./Clientless" and ends with it.

Whatever this error is in reference too, it doesnt prevent the program from being compiled or ran. I made sure to run the program and then logged in on a different account to make sure the bot was actually doing what its programmed to do. And it was.

So if you ask me, everything is good to go! You would be doing me a huge favor if you wanted to do a wiki page covering the various ways to compile for Linux: Arch, Ubuntu, and whatever else you have gotten to work.

**Comment by DavidK1m** [comment]
Just so you know, it worked perfectly on OpenVZ Ubuntu 16.04. Thank you.

**Comment by VoOoLoX** [comment]
@toddw123 I've made wiki page few days ago,I guess I should've mention it.

**Comment by toddw123** [comment]
> @toddw123 I've made wiki page few days ago,I guess I should've mention it.

lol thanks, i dont check the wiki too often so hadnt seen it :)

**Comment by jalius** [comment]
sweet, i'll have to try to get this working on ubuntu (which I have not stopped using ever since I found it).

**Comment by jalius** [comment]
Well, as this is presently working, may I suggest we move it to the wiki?

**Comment by toddw123** [comment]
I think it's been in the wiki for awhile now, it's been awhile since I checked though
