### ISSUE TITLE
commands don't work?

### ISSUE THREAD

**Issue by ghost** [toddw123/RotMG_Clientless#52]
Using latest version of the program, doesnt do anything when you say any of the commands or whisper them to the bot. Havn't changed any code.

**Comment by toddw123** [comment]
They work just fine for me. Just tested again to make sure. So either your bots arent running (you can whisper them, right?) or you could have something like Star Requirement enabled on your main account or whatever account you are using to whisper to them. And i also assume you know that unnamed accounts cant recieve whispers or send whispers, which makes it more likely that you have something like Star Requirement on.

**Comment by toddw123** [comment]
@tomgie did you get them to work? Any update on this? Would be interested to know what could of been causing the problem for you.
