### ISSUE TITLE
Program randomly decides it cant read the char/list xml

### ISSUE THREAD

**Issue by ghost** [toddw123/RotMG_Clientless#55]
Error parsing char/list xml!
Error description: Start-end tags mismatch
Error offset: 65
Error:
<>@gmail.com | Error parsing char/list xml!
Error description: Start-end tags mismatch
Error offset: 65
Error loading config, can not continue program.

I never changed it between compiles but it just decides to stop working

**Comment by Zeroeh** [comment]
You loaded too many accounts in a certain period of time.
