### ISSUE TITLE
Anyone have experience with Visual Studio's github extension?

### ISSUE THREAD

**Issue by toddw123** [toddw123/RotMG_Clientless#7]
I was hoping i could just use the visual studio extension to do all my git related shit (https://visualstudio.github.com/) but it seems that might not be the case. Unless im just an idiot. I use git every day for work but i work in linux and use the git command line. 

Anyways, trying to get the project files added to gitignore so everyone doesnt keep pushing changes that will screw up everyone elses projects. As it is right now, if i go into the command line and do git status, any changes on my project files dont appear. But inside visual studio, if i look at the github window it shows i have uncommitted changes. So anyone know how to fix that? Might just have to use the git command prompt from here on out if this continues.

**Comment by Zeroeh** [comment]
There might be multiple git files detecting different changes.

**Comment by ebf34e12952930cf** [comment]
posted this on the commit but ill post it again i guess

pretty sure you need to empty the cache, try doing this in command line (if you have git)

    git add .
    git rm -r --cached .
    git add .

**Comment by toddw123** [comment]
Yeah i did that before my most recent commit. Ill try it again to see if it helps. I was really liking the visual studio extension so i hope it works correctly, but if not im fine using the command prompt for git.

oh but also like i said, the command line version of git is working like it is suppose to. Its the visual studio extension that isnt.

**Comment by ebf34e12952930cf** [comment]
i tried and it worked for me

![](http://image.prntscr.com/image/f548dd062243446081b8354d79a74b0c.png)

edit: do we really want to remove the sln?

**Comment by toddw123** [comment]
Yeah just did it again and it seems to have worked

**Comment by toddw123** [comment]
Cool everything looks good now, everyone should be able to make changes to their project configs without it fucking everyone elses project configs up (includes/libs/etc).
