### ISSUE TITLE
Path finding

### ISSUE THREAD

**Issue by ebf34e12952930cf** [toddw123/RotMG_Clientless#9]
Have some path finding algorithm (A*?) in Client::moveTo, so you can't walk through walls and stuff.

Need object xml first though, since there's currently no way of knowing what an object is (are we even storing object ids?). This also enables the ability to have an accurate move multiplier.

**Comment by toddw123** [comment]
Yup this is all stuff that is kind far away from being implemented but it is forsure on the list of things i hope make it in. 

Right now objectId's are not being stored, and Objects.xml isnt part of the project yet. I will get objects.xml added within the next week, which yes then i can make use of the moveMultiplier variable in the client class that is just set as 1.0f right now lol.

I originally did add code to make this track bags and turned this into one of those nexus item bots, doing that is pretty easy. But yeah having a way to track objectIds on screen is something i hope to add soon.
